### PR TITLE
Add PCA9554 docs

### PR DESCRIPTION
**Pull request by hwstar**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4192
## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by hwstar** [comment]
Lint fails with: "Error parsing content block for the "list-table" directive: exactly one bullet list expected." Any ideas on how to fix this?

**Comment by nagyrobi** [comment]
The form: `<esphome PR number goes here>` has to be _replaced_ by the PR number...

Also for ckeckmark don't put a space into `[x]`

**Comment by hwstar** [comment]
Those two items are fixed

**Comment by nagyrobi** [comment]
No new line there...

**Comment by hwstar** [comment]
Can I have some context please? Form or the table render problem?

**Comment by nagyrobi** [comment]
I'm still referring to the form.

**Comment by hwstar** [comment]
Fixed

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
