### PR TITLE
Create a flash guide for Sonoff 4CH R3 (as layout and method differs from R2)

### PR DESCRIPTION
**Pull request by arallsopp**
## Description:
The existing methods described in devices/sonoff_4ch.rst are based upon the R2, and do not apply to the current R3 version of this board. The header pins required to flash this board must be added by the end user, are in a different location, and the button used to initiate the flash at boot has a different position and label. 

This PR copies the sonoff_4ch.rst file content as sonoff_4ch_r3 and makes amends to the content to support the revised methods for accessing and flashing this device. It also adds new images to support the revisions, and adds links to the R3 variant in the sonoff and sonoff_4ch pages.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by arallsopp** [comment]
Any action on my part required to get this one rolling?

**Comment by jesserockz** [comment]
First off, please rebase this PR from `current` as it is not linked to a specific feature that will be released with code and can go directly to the live site.

**Review by jesserockz — CHANGES_REQUESTED** [review]
Considering the amount of actual differences between the 4CH and the 4CH R3, I would prefer that it just me merged in with the original 4CH page.

**Comment by arallsopp** [comment]
Fair enough. I can do that. Cheers.

**Pull request closed without merging**
