### PR TITLE
Add more colours for GROW R503-RGB.

### PR DESCRIPTION
**Pull request by Zebble**
GROW R503-RGB variant of R503 includes 4 additional colours.

### CODE REVIEW

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
Can you rebase this PR on the next branch?

**Comment by Zebble** [comment]
I'm a bit of a git noob.  What's the easiest way to do that?

**Comment by oxan** [comment]
If you're not familiar with git, it's probably easiest to create a new PR starting from the `next` branch: https://github.com/esphome/esphome-docs/blob/next/components/fingerprint_grow.rst

**Comment by Zebble** [comment]
Done.  You can delete this PR.  :)

**Pull request closed without merging**
