### PR TITLE
Update netlify python version

### PR DESCRIPTION
**Pull request by jesserockz**
## Description:

This is required to update the build image used on Netlify

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by oxan** [comment]
I _think_ this PR broke the logo in the top-left corner. It doesn't show up and the linked URL gives a 404. It still worked for #1299 (see the deploy preview), and I can't imagine any of the other commits in between breaking it. Haven't looked into why it's broken though.

**Comment by jesserockz** [comment]
Oh, good find. Will take a look. Thanks

**Comment by jesserockz** [comment]
So I just tried locally with the dockerfile and python 3.9 works fine and 3.8 doesnt (which netlify uses) :man_facepalming: 
Different path to the image in html

**Comment by jesserockz** [comment]
https://github.com/sphinx-doc/sphinx/issues/9438

So unrelated to this change, just bad timing

**Comment by oxan** [comment]
Ah, unlucky coincidence.

**Pull request merged**
