### PR TITLE
Create mDNS component documentation

### LINKED ISSUE #2571: New mdns component is not documented
### The problem

In this new version, the `enable_mdns` option under the wifi section has been removed, but it appears in the documentation yet: https://esphome.io/components/wifi.html#configuration-variables

Also I can't find anything about the new `mdns` component in the documentation. Maybe you forgot to merge the documentation, when you merged the functionality

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.5

### What platform are you using?

ESP32

### Board

esp-wrover-kit

### Component causing the issue

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by webeling67**
First version of mDNS component documentation

## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/2571

## Checklist:

  - [x ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by oxan** [comment]
Could you please include the changes from #1570 and #1571 in this PR? There's no need to create a separate PR for every file, and it makes reviewing and merging much harder.

**Comment by berendhaan** [comment]
Let's get this merged, took some time to find this documentation :)

**Comment by oxan** [comment]
> Let's get this merged, took some time to find this documentation :)

Well, that requires someone to bundle all relevant changes into a single PR that can be reviewed ;)

**Comment by oxan** [comment]
Merged into #1662.

**Pull request closed without merging**
