### PR TITLE
Add stevebaxter to supporters.rst

### PR DESCRIPTION
**Pull request by stevebaxter**
## Description:

Please could I be added to the supporters list? I wrote the original implementation of pulse_meter (https://github.com/esphome/esphome/tree/dev/esphome/components/pulse_meter).

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [X] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
I guess you need to add yourself to the CODEOWNERS variable in your code...

**Comment by stevebaxter** [comment]
I'm already there - https://github.com/esphome/esphome/blob/dev/CODEOWNERS#L294

**Comment by nagyrobi** [comment]
Isn't it required to have it also in the code of the component itself?

**Comment by stevebaxter** [comment]
No, it goes in the root https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by nagyrobi** [comment]
Afaik it's in the `__init__.py` of each component in case of ESPHome. See for example:
https://github.com/esphome/esphome/blob/dev/esphome/components/a01nyub/__init__.py
https://github.com/esphome/esphome/blob/dev/esphome/components/ade7880/__init__.py
https://github.com/esphome/esphome/blob/dev/esphome/components/ethernet_info/__init__.py

**Comment by stevebaxter** [comment]
OK, I'll look at that, however it shouldn't stop us merging this. Here's my initial commit for `pulse_meter`:

https://github.com/esphome/esphome/pull/1434

**Comment by stevebaxter** [comment]
@nagyrobi @jesserockz any chance of getting this merged?

**Comment by ssieb** [comment]
> Isn't it required to have it also in the code of the component itself?

It's in the `sensor.py` file.

**Review by ssieb — APPROVED** [review]

**Pull request merged**
