### PR TITLE
MCP23017

### PR DESCRIPTION
**Pull request by lobradov**
## Description:

MCP23017 support. 

**Related issue:** implements OttoWinter/esphomelib#162

**Pull request in [esphomeyaml](https://github.com/OttoWinter/esphomeyaml) with YAML changes (if applicable):** OttoWinter/esphomeyaml#185
**Pull request in [esphomelib](https://github.com/OttoWinter/esphomelib) with C++ framework changes (if applicable):** OttoWinter/esphomelib#218

## Checklist:
  - [ ] The documentation change has been tested and compiles correctly.
  - [ ] Branch: `next` is for changes and new documentation that will go public with the next esphomelib release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Check this box if you have read, understand, comply, and agree with the [Code of Conduct](https://github.com/OttoWinter/esphomedocs/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
LGTM! Thanks!

One thing, the `current` branch is for changes that will be deployed immediately when merged. That branch is mostly for spelling fixes and general improvements.

The `next` branch in the docs repo is for new features. Before each release, that branch will be merged into the `current` branch and deployed. This way users don't see docs for components that don't exist yet as the version isn't out.

Could you change the base branch of this PR to `next` (see https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/)

**Comment by lobradov** [comment]
Changed it. 
btw, I don't have a good picture of the module so that's probably broken.

**Comment by OttoWinter** [comment]
@lobradov You can use these: https://drive.google.com/drive/folders/14DlqVpIEro73rJYTmAZ10wti5djHzFyM :D - The mcp23017-pins.jpg file is not really necessary.

**Comment by OttoWinter** [comment]
Closing due to inactivity.

**Pull request closed without merging**
