### PR TITLE
Adding Inkplate 6 docs

### PR DESCRIPTION
**Pull request by nitko12**
## Description:
Adding documentation for Inkplate 6 e-paper display.

**Related issue (if applicable):** fixes 

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** 
https://github.com/esphome/esphome/pull/1283

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
@nitko12 Please rebase your branch from `next`

**Comment by nitko12** [comment]
@jesserockz where should I rebranch it?

**Comment by jesserockz** [comment]
You should put your commits on a branch that is coming from `next` not `master`

**Comment by nitko12** [comment]
@jesserockz I've made a new PR from next branch :)

**Pull request closed without merging**
