### PR TITLE
Added shelly 2.5

### PR DESCRIPTION
**Pull request by Taigar2015**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Please see ADE7953 - the power chip is already supported (and a fully config is posted there too for temp sensor)

**Comment by Taigar2015** [comment]
I think it is a bit confusing. The shelly 1 and 2 are listed on this page. The shelly 2.5 on another page.
Maybe list the pins on this page, and make a hyperlink to the other page?

**Comment by OttoWinter** [comment]
Yes, that's good - the current PR you have here however says the power chip is not supported, which it is.

**Comment by Taigar2015** [comment]
I didn't mean to say it wasn't supported. I only added the documentation part of the shelly pinout to the list of others.

**Comment by OttoWinter** [comment]
Yeah ok. Though this entry should definitely at least have a link to the power chip - that page contains a more complete example and shows the power chip.

**Pull request closed without merging**
