### PR TITLE
Updated MCP3008 docs with reference_voltage

### PR DESCRIPTION
**Pull request by SenexCrenshaw**
## Description:

Updated the sensor to return the voltage read to match how the ADC component works.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1270

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by OttoWinter** [comment]
I'm not quite sure I understand what you mean. You're trying to update the MCP3008 integration, but the "Files Changed" tab shows a new file.

Please try merging the latest `current` branch into your version (see also "Resolve conflicts" button)

**Comment by jesserockz** [comment]
@SenexCrenshaw Sorry I didnt look at the docs PR until now, this needs to merge into `next` not `current` because the code changes are going into `dev`

**Comment by SenexCrenshaw** [comment]
> @SenexCrenshaw Sorry I didnt look at the docs PR until now, this needs to merge into `next` not `current` because the code changes are going into `dev`

Ok. Ill fix the PR.

**Comment by SenexCrenshaw** [comment]
I closed this in favor of 
#874

**Pull request closed without merging**
