### PR TITLE
H801 LED controller (remade)

### PR DESCRIPTION
**Pull request by erazor666**
## Description:
H801 LED Controller
- Rebased on current
- Compressed and resized images to comply with size requirements
- Misc fixes for the guide document (typos and wording)
- Changed board model

(please delete old PR if it doesn't disappear on its own)

## Checklist:
  - [ ] The documentation change has been tested and compiles correctly.
  - [ ] Branch: `next` is for changes and new documentation that will go public with the next esphomelib release. Fixes, changes and adjustments for the current release should be created against `current`.

### CODE REVIEW

**Comment by OttoWinter** [comment]
I updated the PR with some formatting changes.

However there appears to be something wrong with the `index.rst` file. See the "files" tab, git thinks the whole file changed.

I think your editor is set to CRLF (windows) newline mode. Can you try setting your editor to unix (LF) newline mode?

**Comment by erazor666** [comment]
Sure i can. I've been using visual studio code for the editing. Will look at it later this evening.

Actually, correction. for index.rst i used the github desktop editor.

**Comment by erazor666** [comment]
It looks better now, only 1 line added to index.rst as expected.

**Review by OttoWinter — APPROVED** [review]
Great! Thanks

**Pull request merged**
