### PR TITLE
Add support for additional Xiaomi BLE sensors

### PR DESCRIPTION
**Pull request by ahpohl**
## Description:
The associated pull request esphome/esphome#1027 adds support for many additional Xiaomi BLE devices. To reflect the increased number of supported devices, all devices are now described on one single page, similar to the documentation of the HA custom component [mitemp_bt ](https://github.com/custom-components/sensor.mitemp_bt). The page is divided into following sections:

**Overview**
- General description of Xiaomi BLE devices
- Method to obtain the mac address
- Method to obtain the bindkey for encrypted devices

**Description of individual sensors**
- Special features
- Picture of the device
- Config example

**References**

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1027

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by glmnet** [comment]
can you rebase this on next? there are lots of changes on unrelated files, most likely not checked out on next

**Comment by ahpohl** [comment]
> can you rebase this on next?

My next branch is up-to-date with upstream next. Why do you think this is necessary? How would I do it anyway?

**Comment by glmnet** [comment]
If you go to the files changes tab at the top of this page youll find 100 files, many of those has nothing to do with your work, so this is what I want you to clean up.

I believe this happened because you started working on a ESPHome docs working copy which was pointing to current branch, then you want to merge this in next branch,. There are changes in current which are not in next yet, they sync when we do version releases.

I believe you should
1. checkout next, and git pull so you have latest next version
2. checkout this branch locally, git checkout your next
3. run git rebase -i origin/next 

this should show show you a text file where you should mark which are your commits you want to merge here and others which are foreing which you should ignore.

Check web for examples, if you cannot get it to work I'll try to fix it but please give it a try.

**Comment by ahpohl** [comment]
I've rebased my ahpohl/eshome-docs:next branch onto upstream esphome/esphome-docs:next and squashed all my commits into two commits. Locally it looks fine, but I cannot push this to ahpohl/eshome-docs:next because I do not have the extra commits I wanted to get rid off. 
```
To github.com:ahpohl/esphome-docs.git
 ! [rejected]        next -> next (non-fast-forward)
error: failed to push some refs to 'git@github.com:ahpohl/esphome-docs.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[alex@dell-xps esphome-docs]$ git st
On branch next
Your branch and 'origin/next' have diverged,
and have 2 and 96 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```
What should I do next? Should I create a new local branch and push this instead? This would mean I need to change the PR as well.

**Comment by glmnet** [comment]
This is normal. Git is warning you this pr branch has commits which you don’t have locally. 

No need to create new PR. Just Use -f option with git push

**Comment by ahpohl** [comment]
> No need to create new PR. Just Use -f option with git push

It should be all good now. Should I do the same for https://github.com/esphome/esphome/pull/1027 and rebase ahpohl/esphome:dev onto upstream esphome/esphome:dev and squash all the 172 commits into one?

**Comment by glmnet** [comment]
Thanks, looks good now.

I'll review this later today. The esphome branch is ok, all commits will be squashed and merged by github, please don't change that branch now

**Pull request merged**
