### PR TITLE
Add LibreTiny documentation

### PR DESCRIPTION
**Pull request by kuba2k2**
## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3509

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
What other specific platforms appear with this?
Eg. `libretiny_pwm` is something that likely also needs doc, and appear in the See also footer.

**Comment by kuba2k2** [comment]
> What other specific platforms appear with this? Eg. `libretiny_pwm` is something that likely also needs doc, and appear in the See also footer.

`libretiny_pwm` is the only platform-specific component here. It will be documented too. There's also text sensor with `platform: libretiny`.

**Review by nagyrobi — COMMENTED** [review]
Nice. From the pwm doc a link back to the main platform in the see also section would be nice.

**Comment by kuba2k2** [comment]
Added.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
