### PR TITLE
Add Deltasol 2009

### PR DESCRIPTION
**Pull request by clydebarrow**
## Description:

Add config for new Vbus devices;
rationalise model descriptions.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4943

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by ssieb** [comment]
You deleted the sensor lists.

**Comment by clydebarrow** [comment]
Oops, so I did. I could just restore those lines but I'm inclined to include them in the table of models I created - any thoughts?

**Comment by ssieb** [comment]
If you can do it in a good way, then go for it.

**Comment by clydebarrow** [comment]
Decided that was too hard :-). Should be right now.

**Review by ssieb — APPROVED** [review]

**Pull request merged**
