### PR TITLE
Added warning: GPIOs are LIVE in power measurement devices

### LINKED ISSUE #723: Add warning "danger of death" for devices where GND is live.
**Describe the problem you have/What new integration you would like**

I was about to happily use the GPIOs inside my POW R2, and thankfully I checked with a multimeter. The GND pin is directly connected to the live wire.

My suggestion is to add a clear "warning: danger of death" in [the documentation](https://esphome.io/devices/sonoff.html), specially for devices with power measuring chips since it turns out they completely lack insulation.

**Please describe your use case for this integration and alternatives you've tried:**

New users will find ESPhome a great way to integrate many sensors. Some modules have internal live connections that are not evident for inexperienced users. Specially since the circuit board does _look_ like it has separation between the live area and ESP area. But there is a direct connection between GND and LIVE.

**Additional context**

If there is a warning in the documentation, it is not clear. At least I didn't see it and almost made a dangerous mistake.

### PR DESCRIPTION
**Pull request by CarlosGS**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/723

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by CarlosGS** [comment]
Some examples to justify the slight "alarmism" of the message:

Screenshot_20200509_014624

Screenshot_20200509_014801

Screenshot_20200509_014846

And my own experience: https://github.com/esphome/feature-requests/issues/723#issue-614373990

Let's keep Darwin away! :angel:

**Comment by glmnet** [comment]
It'd be nice to use some kind of include on rst, i'm pretty sure this is possible

**Comment by CarlosGS** [comment]
Hi, sorry I'm not sure how to use the include function (most importantly, not sure where to place the "warning" file in the current structure).
Please feel free to modify or even drop this pull request.

I only miss some sort of message to make people aware of the fully live boards.

**Comment by CarlosGS** [comment]
I've checked this again - the message is at the right places to prevent accidents. Better to be safe than sorry.

I'd also like to have a modular "include" option, but it would be the first time to do so in this repo. And it is not that important, the message would appear in a couple places only (It is not a generic "be careful with electricity" warning, it is specific for some boards).

**Review by glmnet — APPROVED** [review]

**Comment by CarlosGS** [comment]
Please rerun build

**Comment by glmnet** [comment]
You should merge current here and push

**Review by frenck — APPROVED** [review]
Thanks, @CarlosGS 👍

**Pull request merged**
