### PR TITLE
added documentation for the pink version of miflora sensor

### PR DESCRIPTION
**Pull request by fariouche**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5402

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by fariouche** [comment]
any news?

**Review by jesserockz — APPROVED** [review]

**Review by jesserockz — CHANGES_REQUESTED** [review]
I pressed approve then realised that this doesnt use `iaomi_ble` so it really should not be on this page and have its own doc page please.

**Comment by fariouche** [comment]
the reason is that this product is also from xiaomi and is a refresh of the previous one. What other name can I use?

**Comment by fariouche** [comment]
I can move it to xiaomi_hhccjcy10.rst

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
> the reason is that this product is also from xiaomi and is a refresh of the previous one. What other name can I use?

Sorry for the delayed response. THe reason is that the `xiaomi_ble` page is specific to the components that actually use the common `xiaomi_ble` code, which this component does not.

**Pull request merged**
