### PR TITLE
Added manual for Itead Sonoff iFAN03

### PR DESCRIPTION
**Pull request by sliwma**
## Description:

**Related issue (if applicable):** fixes github.com/esphome/feature-requests/issues/784

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
While I expect this works, it would be better to pass through the switches to the custom component:
`new IFan03Output(id(relay_fan1), id(relay_fan2), id(relay_fan3));` and then turn on the switches from the custom component instead of directly using `digitalWrite`

**Comment by sliwma** [comment]
If only I had some time... It is based on the iFan02 config and works for me.

**Comment by ianchi** [comment]
Hi @sliwma @jesserockz, I have some doubts with this recipe.
 

+ what is the purpose of `update_fan_speed`? 
It never gets "called" so the sync never takes place. At least I couldn't see where.

+ why use a custom component? I find it more complicated than necessary. I've accomplished the same with a simple `switch.turn_on` `switch.turn_off` in the `output write_action`.

I leave an example:

```yaml
output:
  - platform: template
    type: float
    id: fan_output
    write_action:
      - if:
          condition:
            lambda: return (state < 0.3);
          then:
            # OFF
            - switch.turn_off: relay_fan1
            - switch.turn_off: relay_fan2
            - switch.turn_off: relay_fan3
      - if:
          condition:
            lambda: return ((state >= 0.3) && (state < 0.6));
          then:
            # LOW SPEED
            - switch.turn_on: relay_fan1
            - switch.turn_off: relay_fan2
            - switch.turn_off: relay_fan3
      - if:
          condition:
            lambda: return ((state >= 0.6) && (state < 0.9));
          then:
            # MID SPEED
            - switch.turn_off: relay_fan1
            - switch.turn_on: relay_fan2
            - switch.turn_off: relay_fan3
      - if:
          condition:
            lambda: return (state >= 0.9);
          then:
            # MAX SPEED
            - switch.turn_off: relay_fan1
            - switch.turn_off: relay_fan2
            - switch.turn_on: relay_fan3
```

**Comment by sliwma** [comment]
Hey, as mentioned - I just modified the iFan02 config to make my iFan03 fully functional.
Your solution looks better tho.

**Pull request closed without merging**
