### PR TITLE
Bump sphinx from 4.3.2 to 5.0.1

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

Bump sphinx to 5.0.1 - This is a major version bump, but none of the breaking changes should apply to our docs and compile output looks fine (including sphinx-autobuild)

https://www.sphinx-doc.org/en/master/changes.html#release-5-0-0-released-may-30-2022

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [N/A] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
One thing I noticed straight away in the netlify preview is that the imgtables do not have equal width columns...

**Comment by OttoWinter** [comment]
> One thing I noticed straight away in the netlify preview is that the imgtables do not have equal width columns...

Nice catch! Yeah it looks like sphinx 4.3.2 (or the alabaster theme, unsure) adds a colgroup at the top of each table
```html
<table class="table-center docutils align-default">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="row-odd">
...
```

whereas sphinx 5 does not emit the colgroup element at all.

**Comment by OttoWinter** [comment]
For reference, the issue was that docutils refactored their table code (`docutils.parsers.rst.directives.tables` module, unfortunately no link because couldn't find a recent docutils git mirror)

**Review by jesserockz — APPROVED** [review]
Cool, checked a few random pages and all looks good to me.

**Comment by jesserockz** [comment]
Seems like the site search may have broken with this bump too...

**Comment by OttoWinter** [comment]
> Seems like the site search may have broken with this bump too...

Yeah can replicate. It appears to be a caching issue though. `https://esphome.io/_static/doctools.js` was updated by sphinx, but my browser cache still has the old version (and some other new js file tries to access variables in doctools.js, which don't exist yet).

For me pressing Ctrl+Shift+R (to force a full reload) solved the issue. Fortunately the cache control header seems to have `must-revalidate` (at least it does now), so this may be fixable by just invalidating the cloudflare cache.

**Pull request merged**
