### PR TITLE
Update htu21d.rst

### PR DESCRIPTION
**Pull request by r0oland**
adding SHT21 as being supported

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by flaviut** [comment]
Would you like to also update the index page? https://github.com/esphome/esphome-docs/blob/current/index.rst

**Comment by r0oland** [comment]
@flaviut Done! I hope I didn't mess things up ;-)

**Comment by r0oland** [comment]
Looks alright to me...
image

**Comment by flaviut** [comment]
Thank you!

**Pull request merged**
