### PR TITLE
Added bottom segment to digit 9

### PR DESCRIPTION
**Pull request by testbughub**
## Description:

This is for the changes made in https://github.com/esphome/esphome/pull/1847

As I've never edited a SVG before, I did it as best as I could.  
I did notice it looked different than the original when comparing,  
so I don't know if this is acceptable.  
I used Inkscape to edit the image.

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
This should be made against `dev` not `current` please

**Comment by testbughub** [comment]
> This should be made against `dev` not `current` please

Oh, sorry!  
Do I make a whole new pr then, or can I do it from this one?

**Comment by jesserockz** [comment]
> > This should be made against `dev` not `current` please
> 
> Oh, sorry!
> Do I make a whole new pr then, or can I do it from this one?

All good, @glmnet updated it and merged it already =)

**Comment by testbughub** [comment]
> > > This should be made against `dev` not `current` please
> > 
> > 
> > Oh, sorry!
> > Do I make a whole new pr then, or can I do it from this one?
> 
> All good, @glmnet updated it and merged it already =)

Sweet!

**Pull request merged**
