### PR TITLE
PCA9554 supporting docs

### PR DESCRIPTION
**Pull request by hwstar**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4184

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
Please fill in the form correctly

**Comment by hwstar** [comment]
Can you be more specific on what's missing in the form? Is it index.rst? Also if someone can look into why the lint is failing in sphynx, that would be helpful.

**Comment by hwstar** [comment]
Pull request is 4184. Added above

**Comment by nagyrobi** [comment]
Fixed it for ya. Also, you need to change the branch to be `next`!!

**Pull request closed without merging**
