### PR TITLE
add documentation for component sn74hc595

### PR DESCRIPTION
**Pull request by phjr**
## Description: This PR adds documentation for new component sn74hc595 (another PR).

**Related issue (if applicable):** N/A

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1083

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by glmnet** [comment]
Ahh this one branch should be next

**Comment by phjr** [comment]
@glmnet which is the correct base branch?

**Comment by glmnet** [comment]
Next

I would change it but I can’t. You should be able to do it. You’ll need to rebase and force push later.

**Comment by phjr** [comment]
@glmnet Done. Thanks for the help with git!

**Pull request merged**
