### PR TITLE
addded ethernet pinouts for SLZB-06

### PR DESCRIPTION
**Pull request by sergge1**
## Description:
Added ethernet pinouts for SMLIGHT SLZB-06

## Checklist:
  - [X] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

### CODE REVIEW

**Comment by nagyrobi** [comment]
Already in the doc ;)

**Comment by sergge1** [comment]
> Already in the doc ;)

Just found it.  Did not see it before PR.
All the devices are one by one, and only SLZB-06 is grouped with some others. 
Hard to find. 
So I will make a new PR as we are listing all the devices but not the Pinouts group (otherwise, we have to group some other devices with the same pinouts in order to be in the same logic)

**Comment by nagyrobi** [comment]
The exact same pinout configuration don't have to be listed twice, it makes the page long and difficult to see.

Currently these two devices share the exact same config, as far as I see, all the others differ at least in one parameter. But as soon as there will appear more devices matching an existing config, it's sure that we won't start duplicating the same code example for each.

This is not a database, nor an advertisment site. Users who search for the information, can find it, that minimum effort is something we expect the users arriving here to be able to do by themselves.

**Comment by nagyrobi** [comment]
Done brusing.

**Pull request closed without merging**
