### PR TITLE
M5 stack relay Documentation

### PR DESCRIPTION
**Pull request by KoenBreeman**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4786

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by KoenBreeman** [comment]
Please reopen since this documentation is needed for the new feature which I implemented

**Comment by kbx81** [comment]
@KoenBreeman I think you need to rebase this -- there are several extraneous files with changes not related to the PR. Please fix and then we can review. Thanks!

**Comment by KoenBreeman** [comment]
> @KoenBreeman I think you need to rebase this -- there are several extraneous files with changes not related to the PR. Please fix and then we can review. Thanks!

I've rebased it against branch: current

**Comment by KoenBreeman** [comment]
Is it ok now?

**Comment by KoenBreeman** [comment]
> Is it ok now?

Is it?

**Comment by kbx81** [comment]
> > Is it ok now?
> 
> Is it?

It is not. Take a look at the number of commits shown above -- there are more than 300. That's not correct. Only your commits should be shown, more like what you see in [this PR](https://github.com/esphome/esphome-docs/pull/3790).

You may need to manually copy out your changes, delete your local branch, make sure your local copy of the `next` branch is up-to-date, recreate your branch (you can use the same branch name) from that, copy your changes back in, commit and finally push it back up to this PR.

**Comment by kbx81** [comment]
> > @KoenBreeman I think you need to rebase this -- there are several extraneous files with changes not related to the PR. Please fix and then we can review. Thanks!
> 
> I've rebased it against branch: current

This is not correct -- since this is a **new** document, you need to be using `next` as your base branch.

**Comment by KoenBreeman** [comment]
> > > @KoenBreeman I think you need to rebase this -- there are several extraneous files with changes not related to the PR. Please fix and then we can review. Thanks!
> > 
> > 
> > I've rebased it against branch: current
> 
> This is not correct -- since this is a **new** document, you need to be using `next` as your base branch.

Oke. I will have a look again. It is been quite some time ago since I made this contribution. So it’s not very motivating to create changes after a couple of years. But I will look into it shortly. I guess I made some mistakes during the update process. I will rebase it to branch ‘next’

**Pull request closed without merging**
