### PR TITLE
IPv6 network component

### PR DESCRIPTION
**Pull request by optimusprimespace**
## Description:
The new #4865 PR enables IPv6 for Arduino framework too, but it enables it by default, hope it was only opt-in not opt-out.
**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [X] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
@HeMan Hm??

**Comment by HeMan** [comment]
> @HeMan Hm??

I think it should be solved by https://github.com/esphome/esphome/pull/5310 and https://github.com/esphome/esphome/pull/5565. 
Is it still not disabling IPv6 when `enable_ipv6` is false?

**Comment by nagyrobi** [comment]
But this PR is invalid then, right?

**Comment by HeMan** [comment]
> But this PR is invalid then, right?

Yes, I should be closed without merging.

**Pull request closed without merging**
