### PR TITLE
New cookbook entry for Ilonda Wifi Smart Fish Feeder (L88)

### PR DESCRIPTION
**Pull request by pplucky**
## Description:
New cookbook entry for Ilonda Wifi Smart Fish Feeder (L88), adapted from existing cookbook entry for a Tuya-based device

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [`next`] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [Yes] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by pplucky — COMMENTED** [review]
Missing picture, should be OK now.

**Comment by pplucky** [comment]
Anything else missing to get this merged, @jesserockz?

**Review by jesserockz — CHANGES_REQUESTED** [review]
While I understand you are just doing what another cookbook has done, please just have a prerequisite to have tuya-convert setup and allow this cookbook to just focus on the ESPHome side of things assuming the user has done that part. Otherwise we will need to update these all when something changes outside the ESPHome project.

**Comment by pplucky** [comment]
> While I understand you are just doing what another cookbook has done, please just have a prerequisite to have tuya-convert setup and allow this cookbook to just focus on the ESPHome side of things assuming the user has done that part. Otherwise we will need to update these all when something changes outside the ESPHome project.

Fully agree with you, but as this was my first cookbook entry, I tried using an existing similar one and adapt it correspondingly.

I think my changes are now fully aligned with your suggestion.

**Review by jesserockz — APPROVED** [review]
LGTM

**Pull request merged**
