### PR TITLE
Documentation for MAX31855 sensor

### PR DESCRIPTION
**Pull request by sherbang**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphomeyaml](https://github.com/OttoWinter/esphomeyaml) with YAML changes (if applicable):** OttoWinter/esphomeyaml#258
**Pull request in [esphomelib](https://github.com/OttoWinter/esphomelib) with C++ framework changes (if applicable):** OttoWinter/esphomelib#310

## Checklist:
  - [✓] The documentation change has been tested and compiles correctly.
  - [✓] Branch: `next` is for changes and new documentation that will go public with the next esphomelib release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [✓] Check this box if you have read, understand, comply, and agree with the [Code of Conduct](https://github.com/OttoWinter/esphomedocs/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by OttoWinter** [comment]
About the image: It's based on [this one](https://ae01.alicdn.com/kf/HTB1eqD0QVXXXXa8XFXXq6xXFXXXj/MAX31855-K-type-thermocouple-module-Pinboard-1350C-SPI-connector-digital-readable-adapter-plate-distinguishability-input-3.jpg_640x640.jpg) right?

If possible, I prefer self-made images because of copyright, but if you can't do that right now I would suggest at least providing attribution 😉

And while we're at it: that image is quite compressed and doesn't look too nice on big displays, could you use this one instead (also in 10x8 aspect ratio, which most images here use for consistency):

max31855

**Comment by sherbang** [comment]
Ok, I took this one today, should I update it to this one?
max31855

**Comment by OttoWinter** [comment]
@sherbang Yes, perfect!

**Comment by OttoWinter** [comment]
Oh shit, sorry pressed wrong button 🤕

**Comment by sherbang** [comment]
Branch updated.  Thanks OttoWinter.

**Pull request merged**
