### PR TITLE
D1 D2 is wrong

### PR DESCRIPTION
**Pull request by hiteshkher**
need code run font part

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by hiteshkher — COMMENTED** [review]
D1 and D2 is wrong also code run need font data and id

**Comment by nagyrobi** [comment]
Why was it wrong?

**Comment by ssieb** [comment]
The examples are not intended to necessarily be fully complete.  They only demonstrate how to setup the specific component.  So you are expected to look at the general display docs to find out how to use fonts.
Also, `D1` and `D2` are not "wrong".  They might not work for your particular board, but again, you're expected to understand about pin definitions and put the ones there that you need.

**Comment by hiteshkher** [comment]
Wrong like sda is not D1 it's D2
                    Scl is not D2 it's D1
So everyone is not cross verify with pin layout and his project is not run
and lot of confusion also not mantion font requirment is not mantion in
this page so biggner have so much time consuming example i spend around 8
to 10 hour  for just display run with basic code so i think if every
example have basic
Code lot of help for biggner.

**Comment by ssieb** [comment]
We're not going to put a full display example on every display component.  You are going to have to look at the display docs to find out how to draw things on the screen anyway.  I would even consider removing the `i2c:` part out of the example as well since it's not really relevant and should just say that you need an `i2c` component configured as well.

**Comment by ssieb** [comment]
Btw, the `SDA` and `SCL` assignments to `D1` and `D2` are arbitrary and only suggestions.  i2c on ESP8266 is software, so it can use most pins.

**Comment by hiteshkher** [comment]
Ok sir
Thank you

**Pull request closed without merging**
