### PR TITLE
Expose select on Frontend `web_server:`

### PR DESCRIPTION
**Pull request by ayufan**
## Description:

This exposes a basic select over a simple frontend
with values taken from traits.

Screen Shot 2021-09-06 at 19 22 31

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** https://github.com/esphome/esphome/pull/2245

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
This also needs to be added to the minified javascript

**Comment by ayufan** [comment]
@jesserockz This is correct. However, I'm unsure how to do it :)

**Comment by jesserockz** [comment]
I have minified it locally, but cannot push to update this PR...

**Comment by ayufan** [comment]
@jesserockz i don’t see an option to edit and allow maintainers. Can you describe how to regenerate it and I will update tomorrow?

**Comment by jesserockz** [comment]
I think the checkbox is on the right hand sidebar somewhere. I just used https://www.npmjs.com/package/minify -> `minify _static/webserver-v1.js > _static/webserver-v1.min.js`

**Comment by ayufan** [comment]
Is not :( maybe because this is in another organization…

**Comment by jesserockz** [comment]
> Is not :( maybe because this is in another organization…

Could be. Not sure on GitHub default policies in that regard.

**Comment by ayufan** [comment]
@jesserockz I also added `make minify` to document that :)

**Review by OttoWinter — APPROVED** [review]

**Pull request merged**
