### PR TITLE
Fingerprint_grow: Add description for on_finger_scan_misplaced trigger

### PR DESCRIPTION
**Pull request by alexborro**
Add description for `on_finger_scan_misplaced` trigger

## Description:

**Related Component:** Fingerprint_grow

**Related issue (if applicable):** New feature: `on_finger_scan_misplaced` trigger

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** https://github.com/esphome/esphome/pull/5365
## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Please also update your PR titles to at least mention the component that changes have been made for.

Thanks

**Comment by alexborro** [comment]
> As this is a feature matched with a PR in esphome/esphome, please target your PR to the next branch and rebase.
> Please also update your PR titles to at least mention the component that changes have been made for.
> Thanks

I will be very happy to rebase it when it has been approved, otherwise I will have to rebase it every week and this PR is open for almost 2 month... 
Cheers.
Alex.

**Comment by nagyrobi** [comment]
Nope. The problem is that it's based against the wrong brach. If you rebase it to the correct branch, it will not need any rebases anymore, just a manual update, which can be done by the reviewer.

Why did you put the checkmark in the checklist to the `next` branch, whilst you worked against `current`?

**Comment by alexborro** [comment]
> Nope. The problem is that it's based against the wrong brach. If you rebase it to the correct branch, it will not need any rebases anymore, just a manual update, which can be done by the reviewer.
> 
> Why did you put the checkmark in the checklist to the `next` branch, whilst you worked against `current`?

Ouch, you are completely right, I thought this was the PR for the code, not docs. Already fixed it and thanks for your patience  ;-)

**Pull request closed without merging**
