### PR TITLE
Update names

### PR DESCRIPTION
**Pull request by fabaff**
## Description:
Update names of other projects.

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
👍

**Comment by brandond** [comment]
@OttoWinter you're back!

**Comment by OttoWinter** [comment]
@brandond Yes! Spent quite a bit of time first working then traveling and unfortunately didn't have much time for esphome. But yes I'm back now :)

**Comment by OttoWinter** [comment]
Oh yes and I should add that I really appreciate the work you and @glmnet did in the past time managing issues and PRs! I'm slowly going back through the backlog (will take some days probably 😐) and then prepare the next release.

**Pull request merged**
