### PR TITLE
Add Lilygo T-Encoder PRO Display to qspi_amoled

### PR DESCRIPTION
**Pull request by mrbubble62**
## Description:
Tested and working with Lilygo T-Encoder PRO display even though the driver chip is SH8601.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by dgaust** [comment]
Thanks for this, even if it's not merged I know the screen works. Did you manage to get the touchscreen working as well?

**Comment by pzich** [comment]
Can you share a full working yaml config for this? I tried adding this along with a simple lambda to draw a line/circle/etc. but couldn't get anything to show up.

**Comment by dgaust** [comment]
> Can you share a full working yaml config for this? I tried adding this along with a simple lambda to draw a line/circle/etc. but couldn't get anything to show up.

This is using the preview LVGL but should get you going

https://github.com/dgaust/esphome_files/blob/main/lilygo-encoder-pro

note: even though there's a reference to a touchscreen in that yaml it's just because I need a touch screen in there - it doesn't actually work.

**Comment by pzich** [comment]
Thanks for sharing, but unfortunately I can't seem to get that one to work either, or even an extremely minimal version of that (without any spi config, etc.):

```yaml
esphome:
  name: lily
  friendly_name: lily

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

psram:
  mode: octal
  speed: 80MHz
```

I always seem to end up with `rst:0x7 (TG0WDT_SYS_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)` ☹️

Strangely, an `arduino` framework type manages to run, connect to wifi, control the buzzer, etc. but the quad SPI isn't available there.

**Comment by pzich** [comment]
It turns out the issue is that I needed to specify the flash mode
```yaml
esphome:
  platformio_options:
    board_build.flash_mode: dio
```

**Pull request closed without merging**
