### PR TITLE
SDM230M important notice to user to pay attention when configuring the energy monitor

### PR DESCRIPTION
**Pull request by optimusprimespace**
## Description:
The SDM230M is a useful power meter, but it doesn't come with the 9600bps default stated in the previous documentation.

**Related issue (if applicable):** fixes <link to issue>
I changed the doc to include the important notice, so if someone makes the same mistake to not change the default baud rate the energy monitor came with to the value that is defined in the example yaml file it won't work.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
Is this related to a new component?
If not, then the branch you need to send your PR against is `current`.

**Comment by optimusprimespace** [comment]
Did i change it successfully? I'm new to github.

**Comment by nagyrobi** [comment]
Much better, thanks.
Why changing SDM220M everywhere to SDM230M?

**Comment by optimusprimespace** [comment]
The sdm230m is a newer model, but i could change it back to sdm220m if everyone is happy with that. :)

**Comment by nagyrobi** [comment]
Did you test the new model yourself?

**Comment by optimusprimespace** [comment]
I've been running it for months without problems.

**Pull request merged**
