### PR TITLE
Update description to 2.9in V2 display variant

### PR DESCRIPTION
**Pull request by darianndd**
As doc extension for this pull request which introduces "2.90inv2-r2" model: https://github.com/esphome/esphome/pull/5481

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5481

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by clydebarrow** [comment]
This should be based on `next`, not `current`, as it relates to new functionality.

**Review by clydebarrow — DISMISSED** [review]
LGTM

**Review by clydebarrow — CHANGES_REQUESTED** [review]
this needs to be based on `next`, not `current`.

**Comment by darianndd** [comment]
> this needs to be based on `next`, not `current`.

Agree, in fact, my pull request to esphome repo introduces a new model. I have changed base branch.

**Review by clydebarrow — APPROVED** [review]

**Pull request merged**
