### PR TITLE
display font: document using gfonts:// for icons

### PR DESCRIPTION
**Pull request by peralta**
Added example showing how to use gfonts to download icons. It seems it is not widely known.

## Description:

Using glyphs from Google's material design library is very common but examples and real usage shows that people are manually downloading the font rather than using esphome's already existing gfonts great helper.

This PR adds an example and explicitly mentions that this is possible.

## Checklist:

  - [X] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

### CODE REVIEW

**Comment by nagyrobi** [comment]
I suggest to also add a `note` about how you calculated the "\U0000e425" codepoint, as it's not straightforward from the MDI site.

**Comment by peralta** [comment]
> I suggest to also add a `note` about how you calculated the "\U0000e425" codepoint, as it's not straightforward from the MDI site.

That is a great suggestion. I found the amount of external links in esphome-docs to be relatively low, so I wonder if such *ad-hoc* instructions are welcome. Happy to provide them.

**Comment by nagyrobi** [comment]
Put it in a `note` box.

**Review by nagyrobi — CHANGES_REQUESTED** [review]
Please add a `note` box with a small explanation on is calculated the "\U0000e425" codepoint, as it's not straightforward from the MDI site.

**Review by nagyrobi — APPROVED** [review]

**Pull request merged**
