### PR TITLE
Added Gitpod documentation

### PR DESCRIPTION
**Pull request by gitolicious**
## Description:
Added Gitpod documentation

**Related issue (if applicable):** fixes <link to issue>
n/a

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#508

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.

### CODE REVIEW

**Review by OttoWinter — CHANGES_REQUESTED** [review]
I don't know gitpod, please explain what it is and why it should be included here.

- I'd prefer this not to be advertised as the easiest way. I've not heard of it being used before so I'm hesitant of marking it as the preferred way until more open source projects use it. Also looks like it costs something after some time using it (a big no).

- See also lint errors.

**Comment by gitolicious** [comment]
Gitpod is on online IDE specifically designed for GitHub projects. I guess you found the web page and the brief intro at https://www.gitpod.io/blog/gitpod-launch/
100 hours a month for open-source projects is free, which I think would suffice for most projects.

To be honest, for me the documentation how to build all ESPHome parts by myself was a bit confusing. Then I remembered I read about the launch of Gitpod last week and gave it a try. Now it's a single click (or 11 letters in your browser address bar) to have your own ESPHome source code in an IDE and it's directly built within seconds with zero installation required.

The configuration file `gitpod.yml` takes care of the required steps. That's all it does. Userscan give it a go and launch a Gitpod instance -- or they can do as before and check out the repo locally, install all dependencies, configure everything on their machine. Nothing wrong with that and no harm done for them.

**Comment by gitolicious** [comment]
The remaining lint errors originate from somewhere else:

> Empty line after heading is missing. Please insert an empty line. See guides/automations.rst:362

> 9:26:05 PM: /opt/build/repo/guides/automations.rst:363:undefined label: sensor-lambda_calls (if the link has no caption the label must precede a section header)

I didn't touch that file.

**Comment by gitolicious** [comment]
Lint errors fixed in https://github.com/esphome/esphome-docs/pull/228 (using GitPod btw 😜)

**Comment by OttoWinter** [comment]
I do think gitpod sounds really cool too, I'm just hesitant to really recommend it until it has been used for a while (and specifically I have also tried it, which I've not yet 🙂 )

About lint error, ah yes that's my bad. base branch has been updated

**Comment by gitolicious** [comment]
Understood. The changed text offers it as an alternative without a firm suggestion. Let's see how it's future developments and adoption will go.

**Comment by gitolicious** [comment]
Now that the documentation includes hints on how to use Gitpod for ESPHome, we should probably also merge the `.gitpod.yml` files as otherwise the "magic" on starting the pods will not happen.
**esphome:** https://github.com/esphome/esphome/pull/508
**esphome-core:** https://github.com/esphome/esphome-core/pull/588
**esphome-docs:** https://github.com/esphome/esphome-docs/pull/226

**Comment by OttoWinter** [comment]
Yeah I know, I just had a massive backlog of issues (and still do). That's why I haven't looked at those yet.

**Pull request merged**
