### PR TITLE
Added degree symbol output on ~ for MAX7219

### PR DESCRIPTION
**Pull request by cyberplant**
## Description:
Added degrees symbol output when input is ~

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#764

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by cyberplant** [comment]
~Please don't merge it yet, I have to create and upload the SVG. And learn how to do it properly in the way~ 😄

**Comment by OttoWinter** [comment]
@cyberplant Ok, if I remember correctly I auto-generated those SVGs with a small script (can't find it anymore though). If you look at the SVG I think you can figure out which segments maps to what to create the layout.

**Comment by cyberplant** [comment]
Yes, I like that idea more than learning how to use inkscape (again, for the 5th time).

Right now I'm super busy with work (as|and) I have holidays next week so I think I'll delay this some days, but I'll work on it soon.

**Comment by cyberplant** [comment]
Hello! I've modified the SVG file manually and now looks good.

I've randomly named the image file with last two characters "8E", as 7E was already used by "0". Is that correct?

**Review by OttoWinter — APPROVED** [review]
Thanks very much! And sorry for the review delay.

Yes the filename is good - no problem.

**Comment by cyberplant** [comment]
No problem.. thanks to you for the great ESPHome!

**Comment by glmnet** [comment]
Ahhh this should be extended to the tm1637 too. Unfortunately it wasn’t committed this one before. But maybe is just adding a line to the tm1637 cpp file

**Pull request merged**
