### PR TITLE
XL9535 I/O Expander

### PR DESCRIPTION
**Pull request by mreditor97**
## Description:

Adding the XL9535 I/O Expander which is used on the Lilygo T-RGB 2.1" Round Display with the ESP32-S3 for additional gpio pins.

*This pull is missing the images. I was hoping that you would be able to generate them for me or tell me how to generate them in the same style as the MXP230xx component at: https://esphome.io/_images/mcp230xx.svg*

This is part of my attempt to add support within ESP Home for the Lilygo T-RGB 2.1" Round Display.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4899

## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by mreditor97** [comment]
@jesserockz Would you be able to tell me how I can create matching images like this: https://esphome.io/_images/mcp230xx.svg which is the same as many other components within the ESP Home docs. I do not have a good quality picture of the part, so an image with the name of the component in would be ideal.

**Comment by jesserockz** [comment]
Haha good question. I tried to actually create a script that would do it for me, but right now I use inkscape to change the text on a `COMPONENT` image, then resize the background, convert text to path and export to plain svg.

XL9535

**Comment by mreditor97** [comment]
Thanks @jesserockz 
I'll look into making some kind of script to make the svg images for us. The documentation for Inkscape isn't great but there has got to be a way!

**Comment by jesserockz** [comment]
I actually took that kick to get my script working nicely =)

I will add it to this repo at some point

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
