### PR TITLE
Add option to activate pulse counter peripheral manual on ESP32

### PR DESCRIPTION
**Pull request by m1ch**
## Description:
Documentation to https://github.com/esphome/esphome/pull/1516 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1516

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by glmnet** [comment]
Please fix this pr, to do so:
```
git reset --hard next
git cherry-pick <relevant commit ids>
git push -f
```

**Comment by glmnet** [comment]
What's perivaral?

**Comment by m1ch** [comment]
> What's perivaral?

The hardware pulse counter peripheral on. In the original implementation it was not possible to select, if you want to use the pulse counter peripheral on esp32, thus only 8 pulse counters where possible on esp32.

**Comment by m1ch** [comment]
> Please fix this pr, to do so:
> 
> ```
> git reset --hard next
> git cherry-pick <relevant commit ids>
> git push -f
> ```

I hope the issue is gone now

**Comment by m1ch** [comment]
> 
> 
> What's perivaral?

💯 Sorry I am dyslexic and did not get, what you mend

**Comment by glmnet** [comment]
Ahh thanks for the clarification. At first I though it was a typo or wrong language then I was more confused.

**Comment by m1ch** [comment]
@glmnet How can I get this and  #1516 to be merged? All checks are passed

**Pull request closed without merging**
