### PR TITLE
Updated Mcp3008 to support reference_voltage and voltage_sampler::VoltageSampler

### PR DESCRIPTION
**Pull request by SenexCrenshaw**
## Description:
Updated the sensor to return the voltage read to match how the ADC component works.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1387

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [] Link added in `/index.rst` when creating new documents for new components or cookbook.

This is just an update to the current doc

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
Please check the example indentation.
Also please don't inflate the example so much. Its best left with the minimum requirements to use the component. eg. don't need the "fridge" config as well. Best if you just add the `reference_voltage` line into the existing example.

**Comment by SenexCrenshaw** [comment]
> Please check the example indentation.
> Also please don't inflate the example so much. Its best left with the minimum requirements to use the component. eg. don't need the "fridge" config as well. Best if you just add the `reference_voltage` line into the existing example.

Sounds good. ill do it over the weekend.

**Comment by SenexCrenshaw** [comment]
Made a few changes and I hope this completed the doc. It was lacking to say the least! Sorry about that

**Comment by SenexCrenshaw** [comment]
@jesserockz I changed the png image to jpg and now the changelog doesnt match throwing a lint error. I could put the file back and have both or do I edit the changelog to point to the right file?

**Comment by jesserockz** [comment]
I think the PNG file is corrupt but because it's still present in the branch it is causing errors. I am only on my phone so can't check properly.

**Review by SenexCrenshaw — COMMENTED** [review]
Thanks!

**Review by SenexCrenshaw — COMMENTED** [review]
Looks good, Thanks!
@jesserockz  is this good to go now?

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
