### PR TITLE
Added equal symbol for MAX7219 7-segment display

### PR DESCRIPTION
**Pull request by egeltje**
## Description:
Show the equal sign = on the max7219 display when the ascii code 0x3d is given.
Done by lighting segments d and g.

**Related issue (if applicable):** none

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#986

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by glmnet** [comment]
This PR should be created against next

**Comment by egeltje** [comment]
> This PR should be created against next

Changed base, but now includes all commits (from other PR's). Do you want a new PR with the correct base ("next")?

**Comment by glmnet** [comment]
Yes. If the commit in esphome is in dev this should be next

You can rebase then force push

**Comment by egeltje** [comment]
> Yes. If the commit in esphome is in dev this should be next
> 
> You can rebase then force push

OK. Will check with a colleague tomorrow. (This is my first PR ever.)

**Comment by glmnet** [comment]
I’m your branch enter

`git rebase next`

Work your way for it to work

Then 

`git push -f`

**Comment by egeltje** [comment]
Created a new PR with the same code against "next". New number is #503 .

**Pull request closed without merging**
