### PR TITLE
added Waveshare BWR Mode for the 7.5in Display

### PR DESCRIPTION
**Pull request by JonasB2497**
## Description:

Added a new display model which enables the BWR rendering mode for the 7.5in v3 display from waveshare.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#7687

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
Please rebase your branch so this PR includes only your changes

**Review by jesserockz — CHANGES_REQUESTED** [review]
Please rebase your branch so this PR includes only your changes

**Comment by JonasB2497** [comment]
I tried to rebase my branch but kind of hit a roadblock. It seems like I have accidentally based my work of of the `current` branch which I think should have been `next` instead (that's why there are so many changes). I have my changes separated in a different branch now based on `next` ([`waveshare_bwr_next`](https://github.com/JonasB2497/esphome-docs/tree/waveshare_bwr_next)) but can't quite figure out the right commands to rebase the branch in this PR.
Do you happen to know the commands I need or can modify this PR to point to my other branch? Or should I just open a new PR and close this one?

**Comment by trip5** [comment]
Hi Jonas.  From Github you should be able to just sync your branch to `esphome-docs:current`... if you get conflict errors, pull the files out that you updated to hold as a backup then rebase it and check if your files are intact.  They should be.

PS I've got a few of these BWR screens.  Is it finally in ESPHome Official?

**Comment by JonasB2497** [comment]
@trip5 syncing deleted my changes but I got it working now by pointing this PR branch to the clean branch I created with `git reset --hard` and then doing a force push. Rebasing to the newest changes then worked in the github UI again.
I have created the necessary changes and created a PR (see the link above) but it is not merged yet.

@jesserockz rebased on the `next` branch now. Hope this as desired although the checks are failing on files I have not changed

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
