### PR TITLE
ENS160 I2C and SPI support

### LINKED ISSUE #2635: SPI Support for ENS160 Air Quality Sensor
**Describe the problem you have/What new integration you would like**

It would be great if SPI Support for the ENS160 Airquality sensor was added. There are many ENS160 sensors which also have an AHT21 Temperature and Humidity sensor on board. 
ENS160+AHT21

Because of the heating element from the ENS160 gas sensor the temperature is always 5 or more degrees higher as the room temperature. So the onboard temperature sensor can not be used for baseline calibration.
There is a library from DFRobot (see link in additional context) which already has SPI Support. Maybe there is a way to integrate the SPI support for the existing ENS160 component in ESPHome.
Because of the SPI connection from the ENS160 sensor you loose the readings from the onboard AHT21. But considering the faulty readings from the onboard AHT21 it is not a disadvantage.

**Please describe your use case for this integration and alternatives you've tried:**

My ENS160+AHT21 airquality sensor was connected via I2C and working fine. I tested it for a few days until I recognized the faulty readings from the onboard AHT21. In my case I ordered a standalone AHT21 sensor, which also connects via I2C. I can not wire both sensors on my one I2C Bus because both AHT21 sensors have the same address 0x38.
I tested the sensors with Arduino IDE and wired the ENS160+AHT21 via SPI to my microcontroller. The standalone AHT21 is wired via I2C Bus and working fine.
So I thought it would be possible to add SPI support for the ENS160+AHT21 sensor to ESPHome. 

**Additional context**

[https://github.com/DFRobot/DFRobot_ENS160.git](https://github.com/DFRobot/DFRobot_ENS160.git)
[https://de.aliexpress.com/item/1005004898420675.html](https://de.aliexpress.com/item/1005004898420675.html)

### PR DESCRIPTION
**Pull request by latonita**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2635

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6369

## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by guillempages** [comment]
@latonita  your description says you want to merge to `next` because it is a new functionality, but your PR is trying to merge to `current`... Could you please fix that?

**Comment by latonita** [comment]
> @latonita your description says you want to merge to `next` because it is a new functionality, but your PR is trying to merge to `current`... Could you please fix that?

@guillempages my bad, fixed.

**Review by guillempages — COMMENTED** [review]
Looks good to me. 
Might need a rebase once the release is done, since there seem to be some extra files changed related to some other PRs that were merged to "current".

**Comment by latonita** [comment]
> Looks good to me. Might need a rebase once the release is done, since there seem to be some extra files changed related to some other PRs that were merged to "current".

Yep, this helped a lot. Thanks

**Review by lastfreemail40 — APPROVED** [review]
Thank you very much. Due to lack of time the testing took a while.

**Review by lastfreemail40 — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
