### PR TITLE
created initial version of documentation of M5stack 4 relay switch 

### PR DESCRIPTION
**Pull request by KoenBreeman**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4786

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by KoenBreeman** [comment]
@jesserockz This is my documentation for M5Stack 4 relay switch. I hope it's up to standard. I see that I've used current, is this ok, or should this be next?

**Comment by jesserockz** [comment]
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

**Comment by KoenBreeman** [comment]
updated documentation

**Comment by KoenBreeman** [comment]
> There hasn't been any activity on this pull request recently. This pull request has been automatically marked as stale because of that and will be closed if no further activity occurs within 7 days. Thank you for your contributions.

This request is marked stale. Can some of the reviewer pick this up??

**Comment by nagyrobi** [comment]
...conflicts need to be resolved...

**Comment by KoenBreeman** [comment]
> ...conflicts need to be resolved...

Weird. I thought everything was fine the last time I checked it in. I’ll check later this evening.

**Comment by KoenBreeman** [comment]
I've created a new pull request, since my base of the document had to be rebased. So new pull request

https://github.com/esphome/esphome-docs/pull/3153

**Pull request closed without merging**
