### PR TITLE
Update svg2png and seo.py

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

`svg2png` is needed because the social headers don't support svgs.

This PR adjusts the script and runs it 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
LGTM. So how does this work exactly, do the social image requests just fallback to try find a png with the same name?

**Comment by OttoWinter** [comment]
See for example this file: https://github.com/esphome/esphome-docs/blob/current/components/stepper/index.rst

at the top it says `folder-open.png` (these images are used by twitter/discord for example for the image you see as a link preview)

Note it's a png, even though the actual file is an svg. The script basically just creates a png version of every svg file (and then get copied to the images folder on build)

**Comment by jesserockz** [comment]
So as well as running this script, we need to not allow people to put .svg in the seo block?

**Comment by OttoWinter** [comment]
I guess so; but we can also just change seo.py to replace svg with png, which should fix it as well

**Comment by OttoWinter** [comment]
Changed it so that now you _have_ to put .svg there, and it checks if the file really exists (hope it won't cause too much trouble for new integrations)

**Pull request merged**
