### PR TITLE
pzemac energy support

### LINKED ISSUE #457: Add pzem004t total energy value (Energy field)
**Describe the problem you have/What new integration you would like**

It would be great (after pzem004t support arrived :rocket:) to also have support for the **total energy value** which is stored in the pzem004t and doesn't reset with a power cut.

This is a super useful value. It's included in all versions of the pzem004t (the old v1+2 and the new v3).

**Please describe your use case for this integration and alternatives you've tried:**

I use it to 'sync' my pzem004t to my mains energy meter :man_scientist: 

I tried to get the same information with the integration component. Problem is that I have my `update_interval:` set to `1s` for the pzem004t component to get real time information. When I add a `restore: true` to the `integration` component I'm worried it will wear out the flash from the esp really quick because it will write the value every second to the flash of the esp (if I understand the docs right).In general I also want avoid to store things on the esp flash.

Another good thing with the value stored inside the pzem004t is that a malfunction of the esp (hardware defect for example) or a communication failure (uart or wifi for example) can't stop it. The pzem004t will continue to measure power usage and stores it - no matter of the other failures. If things are fixed again the total energy consumption reported from the pzem004t will be the correct one. :confetti_ball: 

**Additional context**

https://github.com/esphome/feature-requests/issues/49

### PR DESCRIPTION
**Pull request by rradar**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/457

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** https://github.com/esphome/esphome/pull/933

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by glmnet** [comment]
Reverted as this is already in next where it should have been originally.

**Comment by sendorm** [comment]
What do you mean this is already in? Can we use energy or not?

**Comment by glmnet** [comment]
yes, in ESPHome dev branch

**Comment by sendorm** [comment]
Is there a plan on putting this on master branch?

**Comment by glmnet** [comment]
https://github.com/esphome/feature-requests/issues/658

**Comment by sendorm** [comment]
I still don't get the reasoning of reverting this from master. Not everybody likes to use the dev branch. If one day the master does get an update do the reversion then.

**Comment by glmnet** [comment]
The documentation was added to master by mistake. ESPHome master current version is 1.14.4 and dev is bleeding edge code.
Docs are in sync:
* Docs next https://next.esphome.io -> code dev 
* Docs current https://esphome.io -> code master (v1.14.4 now)

So the commit which enables energy is this one https://github.com/esphome/esphome/pull/933 which is already merged in dev but yet not merged in master (talking about code) so once we do a release current and master gets updated simultaneously.

**Comment by sendorm** [comment]
Ok thank you.

**Pull request merged**
