### PR TITLE
Docs for CS Optional

### LINKED ISSUE #1071: CS pin in SPI should be optional
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP8266, WeMos D1 Mini):**

**Affected component:**

https://esphome.io/components/spi.html

**Description of problem:**
With a single peripheral on the SPI bus, the peripheral's CS pin can be tied to ground, thus saving a pin on the board. Currently, it is not possible to define an SPI peripheral without a CS pin since this pin is required.

**Problem-relevant YAML-configuration entries:**
```yaml
spi:
  clk_pin: D5
  mosi_pin: D7
display:
  - platform: ssd1325_spi
    model: "SSD1325 128x64"
    id: dsply
    reset_pin: D0
#    cs_pin: D1
    dc_pin: D8
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");
```
The above yaml results compilation error:
```
'cs_pin' is a required option for [display.ssd1325_spi].
```
Uncommenting the `cs_pin` line makes compilation work. Leaving the `D1` pin unconnected and tying the display's `CS` pin to ground works.

I have a working fix for this, and will update this comment with a pull request when its ready.
**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by igg**
## Description:

**Related issue (if applicable):** fixes esphome/issues#1071

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#988

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by glmnet** [comment]
Looks good, but you should merge into branch `next` this one

**Comment by igg** [comment]
next and current are very far diverged. I don't want to redo all of this work. Is there an easier way?
If current is not the right branch to make changes to, then why is it the default?
Is this documented somewhere? The template for the PR did not explain adequately this critical piece of information.
What do I do now, close this PR and start over?

**Comment by glmnet** [comment]
did you try

```
git rebase next -i 
```

interactive mode and pick only your commits

**Comment by igg** [comment]
I tried `git rebase origin/next` since `git rebase next` resulted in `fatal: invalid upstream 'next'
`
There is a mass of conflicts after `git rebase origin/next`

**Comment by glmnet** [comment]
use interactive mode... you must pass `-i`

you will be presented with a list of all the commits made in your branch since those branches diverged... you only want to leave there your own commits and remove everything else

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by igg** [comment]
using rebase -i, I deleted all the commits other than mine, and now I have this status:
```
On branch spi-cs-optional
Your branch and 'origin/spi-cs-optional' have diverged,
and have 102 and 89 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```
Doing the recommended `git pull` makes a mess due to a failed auto-merge

**Comment by glmnet** [comment]
So you just left two lines, saved the file closed it and then ended up with all that different commits?

That's really weird.

Forget about the _recommended_ pull

I just did it here, found only two commits from you and only one conflict in atm90e32 because there is something about a 6 channel meter board, I can try to fix and push it if it's ok with you

**Comment by igg** [comment]
It's fine with me. There is only one commit by me though: "Docs for CS Optional" df49784

**Pull request merged**
