### PR TITLE
climate: add support for quiet fan speed

### PR DESCRIPTION
**Pull request by MichaelMure**
## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3609

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by MichaelMure** [comment]
Not stale, I'm waiting on https://github.com/esphome/esphome/pull/3609 to be merged. Please help, someone just need to push the merge button.

**Comment by MichaelMure** [comment]
.

**Comment by ssieb** [comment]
Why is this marked as draft?

**Comment by MichaelMure** [comment]
This is waiting for the corresponding feature: https://github.com/esphome/esphome/pull/3609

I've been asked to demonstrate the full flow up to home assistant, but I'll need some free time to tackle that.

**Comment by ssieb** [comment]
It doesn't need to be marked as draft for that.

**Comment by MichaelMure** [comment]
Different conventions I guess :-)

**Comment by MichaelMure** [comment]
.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
