### PR TITLE
Update doc for Hynitron Microelectronics CST826 capacitive touch

### LINKED ISSUE #2715: Support for Hynitron Microelectronics CST826 capacitive touch
**Describe the problem you have/What new integration you would like**

Support for Hynitron Microelectronics CST826 capacitive touch

**Please describe your use case for this integration and alternatives you've tried:**

Used in folowing boards screens:
* [Adafruit Round RGB 666 TTL TFT Display - 2.1" 480x480 - Capacitive Touch](https://www.adafruit.com/product/5792)
* [MaTouch ESP32 S3 2.1 Rotary TFT with Touch](https://www.makerfabs.com/matouch-esp32-s3-rotary-ips-display-with-touch-2-1-st7701.html)

image

**Additional context**

There is ESPHome support for [cst816 Touch Screen Controller](https://esphome.io/components/touchscreen/cst816.html): 

> This controller is used in the Lilygo T-Display S3 AMOLED. The component should work with CST816T, CST816S, CST820 and CST716 controller chips. 

It was added in this PR: [Add CST816 touchscreen driver #5941](https://github.com/esphome/esphome/pull/5941)

But not yet for CST826: 
 * [CST826 Data sheet. High performance self-capacitance touch chip](https://www.surenoo.tech/download/04_STP/Controller/CST826.pdf)

I've only found these bookshops for the moment as examples:
 * [Adafruit CST8XX Library - Arduino Reference](https://github.com/adafruit/Adafruit_CST8XX_Library)
 * [Adafruit CST8xx capacitive touch driver for CircuitPython](https://github.com/adafruit/Adafruit_CircuitPython_CST8XX)
 
**Schematics**
* [MaTouch-ESP32-S3-Rotary-IPS-Display-with-Touch-2.1 schematic](https://github.com/Makerfabs/MaTouch-ESP32-S3-Rotary-IPS-Display-with-Touch-2.1-ST7701/blob/main/hardware/MaTouch%20ESP32-S3%20Rotary%20IPS%20Display%20with%20Touch%202.1%E2%80%9C%20ST7701%20v1.1.PDF)

### PR DESCRIPTION
**Pull request by lboue**
## Description:
Update doc for Hynitron Microelectronics CST826 capacitive touch chip.

**Related issue (if applicable):** fixes [#2715](https://github.com/esphome/feature-requests/issues/2715)

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6682

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by clydebarrow** [comment]
Should be against `next` as it depends on code not yet released.

**Comment by lboue** [comment]
> Should be against `next` as it depends on code not yet released.

@clydebarrow 
This does not exist in the `next `branch.

**Comment by clydebarrow** [comment]
> This does not exist in the `next `branch.

What do you mean by "this"?

**Comment by lboue** [comment]
Replaced by PR #3831

**Pull request closed without merging**
