### PR TITLE
Add new documentation to SGP40 component

### PR DESCRIPTION
**Pull request by natelust**
## Description:
This adds documentation related to a fix to the SGP40 component.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#2462

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

**Comment by natelust** [comment]
Sorry about that, was not quite sure about the procedure, fixed and pushed

**Review by jesserockz — APPROVED** [review]

**Comment by natelust** [comment]
I see these changes were approved, but not merged. Is there something else you need from me?

**Comment by jesserockz** [comment]
Sorry I closed and reopened to retrigger the CI, then forgot to follow up =)

**Pull request merged**
