### PR TITLE
Recommending input_boolean

### PR DESCRIPTION
**Pull request by jkmaxwell**
I've tried every combination of binary_sensor values from on/off, true/false, 1/0 and each time i get a 

[17:00:14][W][homeassistant.sensor:014]: Can't convert 'False' to number!

(substitute anything for false there)

input_boolean on/off works like a charm, so let's save people some time.

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by jesserockz** [comment]
> [17:00:14][W][homeassistant.sensor:014]: Can't convert 'False' to number!

Based on your log you were using something like this in yaml:
```
sensor: 
  - platform: homeassistant
    entity_id: binary_sensor.some_binary_sensor
    ...
```
instead of 
```
binary_sensor: 
  - platform: homeassistant
    entity_id: binary_sensor.some_binary_sensor
    ...
```

**Comment by jkmaxwell** [comment]
@jesserockz i was using the latter format, consistent binary_sensor in the definition.

```
binary_sensor: 
  - platform: homeassistant
    entity_id: binary_sensor.some_binary_sensor
    ...
```

**Comment by jesserockz** [comment]
But your pasted log line says: `homeassistant.sensor:014` therefore you were using `sensor`

**Comment by jkmaxwell** [comment]
That was from my trying to share it to a template sensor. I'll generate another error log & share soon. Thanks!

**Comment by jkmaxwell** [comment]
Well like the law of all proper demos, now it's working when I try to show it wasn't 😁.

```
[14:37:33][D][homeassistant.binary_sensor:021]: 'binary_sensor.unpleasant_results': Got state ON
[14:37:33][D][binary_sensor:034]: 'My Unpleasant Binary Sensor': Sending initial state ON
```

Let's close this for now and I'll reopen if i see it again

**Pull request closed without merging**
