### PR TITLE
Add GGreg20_V3 Geiger counter to the Cookbook

### PR DESCRIPTION
**Pull request by iotdevicesdev**
## Description:
Add new one Cookbook recipe for another good Geiger counter module (GGreg20_V3) with pulse output that is ESPHome compatible & broadly available on market.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against current.
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
What's the real difference between this and the other Geiger counter already in the cookbook?

**Comment by iotdevicesdev** [comment]
Thank you for your question!
What makes the proposed addition to the Cookbook different is that it is a recipe for connecting another device (GGreg20, not RadiationD module) with two alternative GM tubes (SBM20 / J305) of the user's choice. And so, of course, all meters with pulse output have almost the same principle of operation. Also, each of the recipes has different target users who, for one reason or another, will look for a recipe for their particular device (for some, it is RadiationD, and for others, GGreg20_V3).
Regards,
Oleksii

**Comment by nagyrobi** [comment]
I think it would be better to have one recipe about Geiger - Mueller counter, presenting equally the two variations.

**Comment by iotdevicesdev** [comment]
I am not against this option and even thought of making an addition to the existing document. This can be done by simply adding another device option below in the document. 
What stopped me: 
1. The format of the recipe output to the common catalog (cookbook index) requires an individual photo/picture for each device. 
2. As I could see in other recipes, each recipe is a separate device. 
3. I'm not sure that the author of the existing Geiger counter recipe shares our thoughts on editing the document he created.

**Comment by iotdevicesdev** [comment]
Moved all counter variations into one receipe, under geiger-counter.rst. Please merge into next or current release of Cookbook.

**Comment by nagyrobi** [comment]
I'm sorry to comment again, but things have just changed recently, in the aspect that the https://devices.esphome.io/ site since a few days belongs to this project.

We're reorganizing content now, and decision has been made that device-specific contents will be moved to https://devices.esphome.io/. The advantage is that there will be no constraints on the number of similar devices, so there you can submit your device separately (just like you did here originally).

So I'm respectfully thanking you for your work, but closing this, and invite you to make the PR again at the new site.

**Comment by iotdevicesdev** [comment]
This is very good news. I am happy to add our device to the new website.
Best regards, 
Oleksii
Team IoT-devices, LLC

**Comment by iotdevicesdev** [comment]
Oh! We already have our devices there:
https://devices.esphome.io/devices/IoT-devices-GGreg20-V3

**Comment by nagyrobi** [comment]
Great! Then perhaps if you find any anomaly, just post a fix.

**Pull request closed without merging**
