### PR TITLE
Update pmsx003.rst

### PR DESCRIPTION
**Pull request by hajdbo**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphomeyaml](https://github.com/OttoWinter/esphomeyaml) with YAML changes (if applicable):** OttoWinter/esphomeyaml#<esphomeyaml PR number goes here>
**Pull request in [esphomelib](https://github.com/OttoWinter/esphomelib) with C++ framework changes (if applicable):** OttoWinter/esphomelib#<esphomelib PR number goes here>

## Checklist:
  - [x] The documentation change has been tested and compiles correctly.
  - [x] Branch: `next` is for changes and new documentation that will go public with the next esphomelib release. Fixes, changes and adjustments for the current release should be created against `current`.

### CODE REVIEW

**Comment by hajdbo** [comment]
See https://github.com/esphome/ESPHome-Core/issues/470 and https://github.com/esphome/ESPHome-Core/pull/471

**Comment by hajdbo** [comment]
Doc updated here: https://github.com/esphome/ESPHome-Docs/pull/151

**Review by OttoWinter — COMMENTED** [review]
This PR needs to be rebased (all paths changed, major refactor).

Now that the fix has been merged the message could also be replaced by a link to the FAQ for dev version?

**Comment by hajdbo** [comment]
obsolete

**Pull request closed without merging**
