### PR TITLE
Add Gelidus Research power meter hardware.

### PR DESCRIPTION
**Pull request by descipher**
## Description:

New hardware power meter sensor using the ATM90E32
No code changes required.

## Checklist:

I am merging into `current` because this is new hardware that uses existing code and not for a new component or feature.

### CODE REVIEW

**Comment by nagyrobi** [comment]
@jesserockz should this appear on the front page index too?

**Comment by descipher** [comment]
> @jesserockz should this appear on the front page index too?

Thanks, I can add it there as well.

**Comment by descipher** [comment]
Should be clear on the index page now.

**Comment by descipher** [comment]
Argg, messed this up .. force pushed now

**Comment by nagyrobi** [comment]
Thank you for your contibution.
Things have just changed recently, in the aspect that the https://devices.esphome.io/ site since a few days belongs to this project.

We're reorganizing content now, and decision has been made that device-specific contents will be moved to https://devices.esphome.io/. I'm respectfully thanking you for your work, but closing this, and invite you to make the PR again at the new site.

**Pull request closed without merging**
