### PR TITLE
Update bh1750 docs to use "measurement_duration"

### PR DESCRIPTION
**Pull request by yuvalabou**
## Description:

Update docs to reflect use of measurement duration from core

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1764

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hey @yuvalabou! Thanks for the PR, however, it targeted the `current` branch, while it relies on a parent PR. I've corrected it to target the `next` branch instead.

This now causes additional commits to show up. Could you please git rebase your PR onto the `next` branch? Thanks! 👍 

../Frenck

**Comment by yuvalabou** [comment]
Thanks, rebased

**Comment by frenck** [comment]
@yuvalabou Did you create a new PR? The parent has been merged, but the documentation is now missing.

Anything I can do to help?

**Comment by glmnet** [comment]
I'm going thru some general formatting and found this "issue", I can cherry pick this in my batch fix

**Comment by yuvalabou** [comment]
Please do, I have issues rebasing and until end of next week I don't have much time as there is a war going on 🙄

**Pull request closed without merging**
