### PR TITLE
Sonoff 4CH and Sonoff T1 Touch 3 Gang UK v1.0 cookbooks

### PR DESCRIPTION
**Pull request by meijerwynand**
## Description:

2 new cookbooks to add
* Sonoff T1 Touch 3 Gang UK v1.0
* Sonoff 4CH

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphomeyaml](https://github.com/OttoWinter/esphomeyaml) with YAML changes (if applicable):** OttoWinter/esphomeyaml#<esphomeyaml PR number goes here>
**Pull request in [esphomelib](https://github.com/OttoWinter/esphomelib) with C++ framework changes (if applicable):** OttoWinter/esphomelib#<esphomelib PR number goes here>

## Checklist:
  - [x] The documentation change has been tested and compiles correctly.
  - [x] Branch: `next` is for changes and new documentation that will go public with the next esphomelib release.

### CODE REVIEW

**Comment by meijerwynand** [comment]
Greetings, 

For your review, please inform me should there be something I missed in documentation or with doing the PR.

Thanks

**Comment by OttoWinter** [comment]
I think you misunderstood the next/current thing. For these two PRs, you will need `current` - next is only for new features (like new sensors), those should obviously not show up on the main site until they're released.

Cookbooks etc can be on current (the site you will see when you open esphomelib.com).
This PR still contains commit from your other PRs (see "files" tab). Please create a new branch with these commands:

```bash
git checkout current
# Reset current branch to remote
git fetch origin current
git reset --hard origin/current
# Create new branch
git checkout -b sonoff-4ch
# Cherry-pick commit (see git log)
git cherry-pick ce0b09664e8be9e575bc395859a2081d831fbc37
# Push branch to GH
git push

# For heading in fishpond branch
git checkout current
git checkout -b fix-fisphond-heading
git cherry-pick 3dc9605260e3bbd6fed209d5a4482c515b6a2f3a
git push
```

After that, you can create the PR in github interface as before. Git is hard, I know, but if I merge this branch as-is I will get lots of merge conflicts and the git history will be messed up.

**Comment by meijerwynand** [comment]
Thank you for the clarification on the `next` and current `branches`.

I will follow your instructions and appreciate the assistance.

**Comment by OttoWinter** [comment]
Closing due to inactivity (and many paths have changed).

**Pull request closed without merging**
