### PR TITLE
Example for ESP32S3_EYE on Freenove ESP32-S3-DevKitC-1

### PR DESCRIPTION
**Pull request by mclazer**
## Description:
Updated the docs to include an example on how to include the ESP32S3_EYE on Freenove ESP32-S3-DevKitC-1 with an external component entry.

**Related issue (if applicable):** fixes 

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
I think this should rather go in the cookbook, with some additional description. Here just a link in the SeeAlso section to the cookbook entry.

**Comment by mclazer** [comment]
> I think this should rather go in the cookbook, with some additional description. Here just a link in the SeeAlso section to the cookbook entry.

Is this just a recommendation or a hard requirement?

**Comment by mclazer** [comment]
Is there any update? What exactly is blocking this PR to be merged?

**Comment by nagyrobi** [comment]
As soon as you follow the recommendation :-)

**Review by nagyrobi — APPROVED** [review]

**Comment by nagyrobi** [comment]
Don't be unpatient

**Pull request merged**
