### PR TITLE
Include Note about TMC2208 Modules

### PR DESCRIPTION
**Pull request by vBJohannes**
## Description:
As TMC2208 modules are mostly compatible with A4988 modules, there is a way to use this library to also drive an TMC2208. Only slight changes according to the different pinout need to be accounted for.

**Related issue (if applicable):** There is no particular issue I had in mind.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** not applicable

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by nagyrobi — COMMENTED** [review]
I think you should be more specific rather than just saying _check online_...

**Comment by vBJohannes** [comment]
I don't get the error in the Lint build, tbh.

**Review by nagyrobi — DISMISSED** [review]

**Comment by vBJohannes** [comment]
Apparently the lint check is happy once I indented the table. Merge, please :)

**Comment by ssieb** [comment]
I don't understand how this would be configured with the two pins.  Can you expand the example to be a full config?

**Comment by vBJohannes** [comment]
> I don't understand how this would be configured with the two pins. Can you expand the example to be a full config?

How about now?

**Comment by nagyrobi** [comment]
This should be resubmitted as a PR against `current` branch, please.

**Pull request closed without merging**
