### PR TITLE
Documentation of ds248x component

### PR DESCRIPTION
**Pull request by alainstark**
## Description:

Documentation of ds248x component

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6616

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
Please check the linter warnings and fix them (eg. no tabs allowed).

**Comment by martijnbuts** [comment]
Hi can you take a look at the type, i added the component but the "type: ds2482-100" is not accepted. Also the channel is not needed for the type: ds2482-100. For the rest nice work and i hope it get merged soon :)

**Comment by lboue** [comment]
@alainstark

The `type `setting is specified as mandatory in the documentation. However, when this parameter is set, it generates an error.

`   [type] is an invalid option for [ds248x]. Please check the indentation.`

**Test config**
```
ds248x:
  i2c_id: bus_b
  type: ds2484
  address: 0x18 # should be the default
```

**Comment by lboue** [comment]
@alainstark 

Could you accept my PR [Improve Ds248x documentation #1](https://github.com/alainstark/esphome-docs/pull/1/files) ?

**Pull request closed without merging**
