### PR TITLE
New branding for ESPHome

### PR DESCRIPTION
**Pull request by Madelena**
## Description:
* New Logo
* New favicons
* Changed typography of the website to match the new branding.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by nagyrobi** [comment]
New font introduces too big line spacing. Looks a bit fell apart. Would worth reducing line spacing to make it look more consolidated.

**Comment by nagyrobi** [comment]
Thanks! A bit better now. Could we try maybe a `line-height: 1.5;` too to see how it would look like with that?

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
> Thanks! A bit better now. Could we try maybe a `line-height: 1.5;` too to see how it would look like with that?

I just had a quick play with the line-height, and yes I think it should be less too.. 
I'm not a designer though, will let @Madelena decide on that.

**Comment by jesserockz** [comment]
I will merge for today though and we can adjust the line-height separately

**Pull request merged**
