### PR TITLE
New cookbook entry: DC Power logger 

### PR DESCRIPTION
**Pull request by wesleygas**
## Description:

A new cookbook entry showing how to build a power logger that can also write to an sdcard. It uses a custom component to deal with the time uncertainties while integrating the measurements from the already present INA219 integration.

**Related issue (if applicable):** -

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** -

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
This PR seems to target an incorrect branch. As this PR doesn't rely on a parent PR in the ESPHome main code base, this PR should have been targeted against the `current` branch.

Could you please change the target branch of this PR to `current` and perform a git rebase onto `next` if that is needed to clean out unrelated PRs?

Thanks! 👍 

../Frenck

**Comment by wesleygas** [comment]
Sure! I targeted the ``next`` because of the first checklist item, but I guess I've misinterpreted it. Thanks for pointing it out

**Comment by frenck** [comment]
Yes, thanks! However, now there are all kinds of unrelated commits in this PR. In order to resolve that, you'll need to git rebase this PR onto the `current` branch.

**Comment by wesleygas** [comment]
I guess it did not work hehe.... I'll just close this one and open another PR targeting the correct branch

**Pull request closed without merging**
