### PR TITLE
Specify format for BSSID entries.

### PR DESCRIPTION
**Pull request by marcteale**
## Description:
Clarify format of BSSID entry.

**Related issue (if applicable):** n/a

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#
n/a

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by jesserockz — COMMENTED** [review]
Do we really need this? Especially without actually giving an example?
ESPHome will give a config validation error on trying to compile with an incorrectly formatted mac address anyway and also give the example of `XX:XX:XX:XX:XX:XX`

**Comment by marcteale** [comment]
Either the configuration validation needs to be updated, or the documentation, or both.  While the validation rejects an improperly formatted MAC address (e.g. a hyphen-delimited entry), it accepts lowercase letters.  Firmware compiled with a lowercase entry will not be able to find the specified BSSID.  I also feel it's poor UX if the only way to determine the correct format is to receive a compile time error.

That said, if the edit would benefit from an example, I'm happy to make the change.

**Comment by jesserockz** [comment]
Thats unfortunate. If that is the case, then the config validation should be enforcing or converting to uppercase.

**Comment by jesserockz** [comment]
So I just tested the config, and it converts them to hex integers, and the main.cpp file is no different if you use upper or lower case...

**Comment by marcteale** [comment]
I just did some testing of my own and got the same results.  I think the connection failures that spawned this pull request were the result of a dying/flaky WAP.

**Comment by frenck** [comment]
Looking at the discussion above, and the contents of this PR:

 @marcteale If you really think this is an issue, please raise an issue in the issue tracker, so we can keep track of it and discuss it until resolved. A documentation PR might not be the right place to track it :)

Personally, as for the contents of this PR, I think it doesn't harm to add it. At best, people know what to do before being hit by the config validation. So I would vote on adding it. @jesserockz What do you think?

**Review by frenck — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]
Ok, lets get this in then =)

**Pull request merged**
