### PR TITLE
Draft PR explanation

### PR DESCRIPTION
**Pull request by jesserockz**
## Description:

This adds an explanation as to why PRs would be converted to draft PRs by the bot on GitHub

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
Looks good.
But lets draft this for now (not merge it at least) until the bot is ready, it currently does not exist in this org.
So it does not add confusion before its actually ready.

**Comment by nagyrobi** [comment]
Wow, nice.
Will this apply to all repos? `esphome`, `esphome-docs` etc?

**Comment by nielsnl68** [comment]
I like this. It is almost the idea i suggested as in make all new PR's automatedly a draft.

**Comment by ludeeus** [comment]
> Will this apply to all repos? esphome, esphome-docs etc?

Yes, this is enabled on all repositories in the org.

**Pull request merged**
