### PR TITLE
Document sensor id and how it relates to the name

### PR DESCRIPTION
**Pull request by Cat-Ion**
## Description:

Document the existance of `id` and that `name` is not required if `id` exists

**Related issue (if applicable):** None

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** None

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by mbo18** [comment]
If `id` is added here, should it be removed from all sensors documentation where it is written `All other options from Sensor. `?
Like here: https://esphome.io/components/sensor/sgp30.html
Or here: https://esphome.io/components/sensor/homeassistant.html

**Comment by Cat-Ion** [comment]
Probably, yes. At least that's certainly less work than making everything have both options, and making sure that they're documented the same way.

**Comment by flaviut** [comment]
@Cat-Ion Would you be willing to make that change?

**Comment by Cat-Ion** [comment]
Yes, but I'm going to need a bit because I'm absolutely swamped at work right now.

**Comment by OttoWinter** [comment]
No, I don't think it should be removed elsewhere. We have the most important options in each sensor block, and ID is something more users may want to use to chain together things etc.

**Review by OttoWinter — APPROVED** [review]
Thanks!

**Pull request merged**
