### PR TITLE
Fix docs for inkplate

### PR DESCRIPTION
**Pull request by NobodysNightmare**
Version 1.17.0 seems to have changed this, according to an error message I received :)
Updating the docs accordingly.

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

### CODE REVIEW

**Comment by NobodysNightmare** [comment]
Sidenote: I was slightly confused that I had to edit two documents (inkplate and inkplate6), botht seem to have the same content, specific to the inkplate6.

**Comment by glmnet** [comment]
`Inkplate.rst` should be deleted. And this should be **current** branch

**Review by frenck — CHANGES_REQUESTED** [review]
Adjusting review state of this PR.

**Comment by NobodysNightmare** [comment]
I deleted the `inkplate.rst`. As far as I can tell I am already targeting the `current` branch.

**Comment by NobodysNightmare** [comment]
Wait a second... The index seems to be referring to `inkplate`, not `inkplate6`. I guess I need to adapt this as well, then?

**Comment by NobodysNightmare** [comment]
Okay, so I now link to `inkplate6` from the index and I cleaned up the images:

* `Inkplate.jpg` was deleted
* `inkplate.jpg` was renamed to `inkplate6.jpg` and references have been updated.

**Review by frenck — APPROVED** [review]
Thanks, @NobodysNightmare 👍 

../Frenck

**Pull request merged**
